"""empty message

Revision ID: be9d6f1b7f41
Revises: ae8e739d540f
Create Date: 2024-05-25 13:48:37.874639

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "be9d6f1b7f41"
down_revision = "ae8e739d540f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("course_group", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "position", sa.Integer(), server_default=sa.text("'1'"), nullable=False
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("course_group", schema=None) as batch_op:
        batch_op.drop_column("position")

    # ### end Alembic commands ###
